// Compile src/library/sounds/*.json into the shipped TypeScript bundle.
// Exported as a function because the review server rebuilds after it
// accepts a candidate, and a second copy of this logic would drift.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export type BuildResult = { ok: boolean; output: string };

const repoRoot = (): string => join(dirname(fileURLToPath(import.meta.url)), '..');

export function buildLibrary(root: string = repoRoot()): BuildResult {
  const soundsDir = join(root, 'src', 'library', 'sounds');
  const outputFile = join(soundsDir, 'generated.ts');
  try {
    const files = readdirSync(soundsDir)
      .filter((file) => file.endsWith('.json'))
      .sort();
    const entries = files.flatMap((file) => JSON.parse(readFileSync(join(soundsDir, file), 'utf8')) as unknown[]);
    const header = '// Generated by scripts/build-library.ts from src/library/sounds/*.json. Do not edit by hand.\n';
    const body = `import type { SoundEntry } from '../types';\n\nexport const sounds: SoundEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
    writeFileSync(outputFile, header + body);
    return { ok: true, output: `Wrote ${entries.length} entries from ${files.length} files to ${outputFile}` };
  } catch (error) {
    return { ok: false, output: error instanceof Error ? error.message : String(error) };
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const result = buildLibrary();
  console.log(result.output);
  process.exit(result.ok ? 0 : 1);
}
