#!/usr/bin/env node
// scripts/build-library.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const soundsDir = join(__dirname, '..', 'src', 'library', 'sounds');
const outputFile = join(soundsDir, 'generated.ts');

const files = readdirSync(soundsDir)
  .filter((file) => file.endsWith('.json'))
  .sort();

const entries = files.flatMap((file) => JSON.parse(readFileSync(join(soundsDir, file), 'utf8')));

const header = '// Generated by scripts/build-library.mjs from src/library/sounds/*.json. Do not edit by hand.\n';
const body = `import type { SoundEntry } from '../types';\n\nexport const sounds: SoundEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

writeFileSync(outputFile, header + body);
console.log(`Wrote ${entries.length} entries from ${files.length} files to ${outputFile}`);
