import { describe, it, expect } from 'vitest';
import { pick, render, run } from './pick';
import { sounds } from './library/index';

describe('pick', () => {
  it('takes an exact name', () => {
    const result = pick(['upload-complete']);
    expect(result.entries.map((e) => e.name)).toEqual(['upload-complete']);
    expect(result.matched[0]?.how).toBe('name');
    expect(result.missing).toEqual([]);
  });

  it('takes plain prose', () => {
    const result = pick(['my washing machine finished']);
    expect(result.entries.map((e) => e.name)).toEqual(['washer-done']);
    expect(result.matched[0]?.how).toBe('prose');
  });

  it('mixes names and prose, and keeps the order given', () => {
    const result = pick(['error-buzz', 'a dog barking', 'tap']);
    expect(result.entries.map((e) => e.name)).toEqual(['error-buzz', 'dog-bark', 'tap']);
  });

  it('drops a repeat, however it was asked for', () => {
    const result = pick(['upload-complete', 'the file finished uploading', 'upload-complete']);
    expect(result.entries.length).toBe(1);
    // Every request is still reported, so a caller sees what happened.
    expect(result.matched.length).toBe(3);
  });

  it('reports a request that matched nothing instead of dropping it', () => {
    const result = pick(['tap', 'quantum entanglement']);
    expect(result.entries.map((e) => e.name)).toEqual(['tap']);
    expect(result.missing).toEqual(['quantum entanglement']);
  });

  it('ignores blank requests', () => {
    expect(pick(['', '   ', 'tap']).entries.length).toBe(1);
  });

  it('searches only inside the set it is given', () => {
    const subset = sounds.filter((s) => s.category === 'animals');
    const result = pick(['a dog barking', 'the upload finished'], subset);
    expect(result.entries.every((e) => e.category === 'animals')).toBe(true);
  });
});

describe('render', () => {
  it('writes a TypeScript module with the entry type', () => {
    const out = render(pick(['tap']).entries, 'src/sounds.ts');
    expect(out).toContain("import type { SoundEntry } from 'semantic-sounds';");
    expect(out).toContain('export const sounds: SoundEntry[] =');
    expect(out).toContain('Generated by `semantic-sounds-pick`');
    expect(out).toContain('"name": "tap"');
  });

  it('writes plain JavaScript with no type import', () => {
    const out = render(pick(['tap']).entries, 'src/sounds.js');
    expect(out).not.toContain('import type');
    expect(out).toContain('export const sounds =');
  });

  it('writes bare JSON that parses back to the entries', () => {
    const entries = pick(['tap', 'error-buzz']).entries;
    const parsed = JSON.parse(render(entries, 'src/sounds.json')) as typeof entries;
    expect(parsed).toEqual(entries);
  });

  it('warns against importing the whole set as well', () => {
    expect(render(pick(['tap']).entries, 'a.ts')).toContain('do not');
  });

  it('is much smaller than the whole set', () => {
    const few = render(pick(['tap', 'error-buzz', 'upload-complete']).entries, 'a.json').length;
    const all = JSON.stringify(sounds).length;
    // Three of 1090. The saving is the whole reason this exists.
    expect(few).toBeLessThan(all / 100);
  });
});

describe('the command line', () => {
  it('writes the module and reports what it matched', () => {
    const { code, out, report } = run(['tap', 'a dog barking', '--out', 'src/sounds.ts']);
    expect(code).toBe(0);
    expect(out).toContain('export const sounds: SoundEntry[]');
    expect(report).toContain('2 of ');
    expect(report).toContain('dog-bark   <- "a dog barking"');
  });

  it('fails when a request matched nothing', () => {
    // A silent drop would ship an app whose button makes no sound.
    const { code, report } = run(['tap', 'quantum entanglement']);
    expect(code).toBe(1);
    expect(report).toContain('nothing matched "quantum entanglement"');
  });

  it('shows usage with no arguments, and fails', () => {
    const { code, report } = run([]);
    expect(code).toBe(1);
    expect(report).toContain('Usage: semantic-sounds-pick');
  });

  it('shows usage on --help, and succeeds', () => {
    const { code, report } = run(['--help']);
    expect(code).toBe(0);
    expect(report).toContain('Usage: semantic-sounds-pick');
  });

  it('defaults to a TypeScript module when no --out is given', () => {
    expect(run(['tap']).out).toContain('import type { SoundEntry }');
  });

  it('matches the format to the --out extension', () => {
    expect(run(['tap', '--out', 'x.json']).out.trimStart().startsWith('[')).toBe(true);
    expect(run(['tap', '-o', 'x.js']).out).toContain('export const sounds =');
  });
});
