#!/usr/bin/env node
// Write a module that holds only the sounds an app uses.
//
//   npx semantic-sounds-pick upload-complete "a dog barking" --out src/sounds.ts
//
// Why this exists. A runtime helper that filters the set does not shrink
// anything: a bundler cannot drop entries from an array it does not
// understand, so the whole set still ships. The only thing that shrinks a
// bundle is a smaller source file. This writes that file.
//
// The app then imports the generated module and nothing else from this
// package's sound set:
//
//   import { sounds } from './sounds';
//   const api = createSemanticSounds({ sounds });
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { sounds, createSoundIndex, searchIndex, LOCAL_MIN_SCORE, type SoundEntry } from './library/index';

export type PickResult = {
  entries: SoundEntry[];
  /** What each request matched, in the order given. */
  matched: { request: string; name: string; how: 'name' | 'prose' }[];
  /** Requests that matched nothing. */
  missing: string[];
};

/**
 * Turn a list of names and prose queries into a set of entries.
 *
 * A name is exact. Anything else is searched, so `"a dog barking"` works
 * as well as `dog-bark`. The result holds no duplicates and keeps the
 * order the requests came in.
 */
export function pick(requests: readonly string[], set: readonly SoundEntry[] = sounds): PickResult {
  const byName = new Map(set.map((entry) => [entry.name, entry]));
  let index: ReturnType<typeof createSoundIndex> | null = null;

  const entries: SoundEntry[] = [];
  const seen = new Set<string>();
  const matched: PickResult['matched'] = [];
  const missing: string[] = [];

  for (const request of requests) {
    const term = request.trim();
    if (term.length === 0) continue;

    let found = byName.get(term);
    let how: 'name' | 'prose' = 'name';
    if (!found) {
      index ??= createSoundIndex(set as SoundEntry[]);
      const best = searchIndex(index, term, { limit: 1, minScore: LOCAL_MIN_SCORE })[0];
      found = best?.sound;
      how = 'prose';
    }

    if (!found) {
      missing.push(term);
      continue;
    }
    matched.push({ request: term, name: found.name, how });
    if (seen.has(found.name)) continue;
    seen.add(found.name);
    entries.push(found);
  }

  return { entries, matched, missing };
}

/** The generated module. TypeScript by default, JSON when the path says so. */
export function render(entries: readonly SoundEntry[], target: string): string {
  if (target.endsWith('.json')) return `${JSON.stringify(entries, null, 2)}\n`;

  const head = [
    '// Generated by `semantic-sounds-pick`. Do not edit.',
    '//',
    `// ${entries.length} of ${sounds.length} sounds. Import this module, and do not`,
    "// import `sounds` from 'semantic-sounds', or the whole set ships as well.",
    '',
  ];
  const typed = target.endsWith('.ts') || target.endsWith('.tsx');
  if (typed) {
    head.push("import type { SoundEntry } from 'semantic-sounds';", '');
    head.push(`export const sounds: SoundEntry[] = ${JSON.stringify(entries, null, 2)};`, '');
  } else {
    head.push(`export const sounds = ${JSON.stringify(entries, null, 2)};`, '');
  }
  return head.join('\n');
}

function usage(): string {
  return [
    'Usage: semantic-sounds-pick <name-or-phrase>... [--out FILE]',
    '',
    'Write a module holding only the sounds you name, so an app bundle',
    'carries twenty patches instead of all 1090.',
    '',
    '  --out FILE   where to write. .ts, .tsx, .js or .json. Default: stdout.',
    '',
    'Examples:',
    '  npx semantic-sounds-pick tap success-chime --out src/sounds.ts',
    '  npx semantic-sounds-pick "the upload finished" "a dog barking" --out src/sounds.json',
  ].join('\n');
}

export function run(argv: readonly string[]): { code: number; out: string; report: string } {
  const requests: string[] = [];
  let target = '';

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]!;
    if (arg === '--out' || arg === '-o') {
      target = argv[++i] ?? '';
      continue;
    }
    if (arg === '--help' || arg === '-h') return { code: 0, out: '', report: usage() };
    requests.push(arg);
  }

  if (requests.length === 0) return { code: 1, out: '', report: usage() };

  const result = pick(requests);
  const lines = result.matched.map((m) =>
    m.how === 'name' ? `  ${m.name}` : `  ${m.name}   <- "${m.request}"`
  );
  for (const miss of result.missing) lines.push(`  (nothing matched "${miss}")`);

  const report = [
    `${result.entries.length} of ${sounds.length} sounds`,
    ...lines,
    result.missing.length > 0 ? `\n${result.missing.length} request(s) matched nothing.` : '',
  ]
    .filter(Boolean)
    .join('\n');

  // A request that matched nothing is a fault, not a warning. A silent
  // drop would ship an app whose button makes no sound.
  return { code: result.missing.length > 0 ? 1 : 0, out: render(result.entries, target || '.ts'), report };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const argv = process.argv.slice(2);
  const { code, out, report } = run(argv);
  const outIndex = Math.max(argv.indexOf('--out'), argv.indexOf('-o'));
  const target = outIndex === -1 ? '' : (argv[outIndex + 1] ?? '');

  if (out && target) {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, out);
    console.error(report);
    console.error(`\nWrote ${target}`);
  } else if (out) {
    console.log(out);
    console.error(report);
  } else {
    console.error(report);
  }
  process.exit(code);
}
